# Generated by Django 2.0.3 on 2018-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('associate', '준회원'), ('corporate', '기업회원'), ('regular', '정회원'), ('author', '작가회원')], max_length=40, verbose_name='등급'),
        ),
    ]
