# Generated by Django 2.0.3 on 2018-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180419_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_status',
            field=models.CharField(choices=[('private', '비공개'), ('public', '공개')], default='public', max_length=40, verbose_name='상태'),
            preserve_default=False,
        ),
    ]
