# Generated by Django 2.0.3 on 2018-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_open_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='status',
            field=models.CharField(choices=[('requested', '요청'), ('approved', '수락'), ('auto_approved', '자동수락')], max_length=40, verbose_name='요청상태'),
        ),
    ]
