# Generated by Django 2.0.3 on 2018-05-14 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('operations', '0001_initial'),
        ('accounts', '0007_auto_20180512_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromotionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.PromotionCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
