# Generated by Django 2.0.3 on 2018-05-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userpromotioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpromotioncode',
            name='used_at',
        ),
        migrations.AlterField(
            model_name='userpromotioncode',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='operations.PromotionCode'),
        ),
        migrations.AlterField(
            model_name='userpromotioncode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
