# Generated by Django 2.0.3 on 2018-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180514_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_route',
            field=models.CharField(choices=[('lineup', '라인업 직접가입'), ('steem', '스팀 계정')], default='lineup', max_length=40, verbose_name='가입경로'),
        ),
    ]
