# Generated by Django 2.1.5 on 2019-04-30 14:01

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_code',
            field=models.CharField(editable=False, max_length=8, unique=False, null=True, blank=True, verbose_name='추천인 코드'),
        ),
    ]
