# Generated by Django 2.1.5 on 2019-04-30 14:01

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_recommended_code(apps, schema_editor):
    from ..models import _default_recommended_code
    User = apps.get_model('accounts', 'User')
    for o in User.objects.all():
        o.recommended_code = _default_recommended_code()
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190430_1401'),
    ]

    operations = [
        migrations.RunPython(create_recommended_code),
        migrations.AlterField(
            model_name='user',
            name='recommended_code',
            field=models.CharField(default=accounts.models._default_recommended_code, editable=False, max_length=8, unique=True, null=False, blank=False, verbose_name='추천인 코드'),
        ),
    ]
