# Generated by Django 2.0.3 on 2018-05-14 15:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=32, unique=True, verbose_name='프로모션 코드')),
                ('extra', django_mysql.models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_quantity', models.PositiveSmallIntegerField(default=0)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
