# Generated by Django 2.0.3 on 2018-05-30 08:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='allow_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='허용 사용 개수'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료일시'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='extra',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 상태'),
        ),
    ]
