# Generated by Django 2.0.3 on 2018-07-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_reportpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('drafted', '임시저장'), ('published', '발행'), ('marked_hidden', '숨김처리')], default='draft', max_length=40, verbose_name='상태'),
        ),
    ]
