# Generated by Django 2.0.3 on 2018-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20180715_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('drafted', '임시저장'), ('published', '발행'), ('marked_hidden', '숨김처리'), ('deleted', '삭제대기')], default='draft', max_length=40, verbose_name='상태'),
        ),
    ]
