# Generated by Django 2.0.3 on 2018-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_behaviour_behaviourpointlog_pointstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='code',
            field=models.CharField(max_length=80, unique=True, verbose_name='행동코드'),
        ),
    ]
