# Generated by Django 2.0.3 on 2018-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20181130_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='reward',
            field=models.SmallIntegerField(default=0, verbose_name='행동 보상 포인트'),
        ),
    ]
