# Generated by Django 2.0.3 on 2018-11-30 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20181130_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourpointlog',
            name='point',
            field=models.SmallIntegerField(help_text='적립 시점의 포인트', verbose_name='행동 포인트'),
        ),
        migrations.AlterField(
            model_name='pointstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
