# Generated by Django 2.0.3 on 2018-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20181130_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourpointlog',
            name='reason',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='사유 코드'),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='code',
            field=models.CharField(help_text='소문자, `_` 기호만 허용.', max_length=80, unique=True, verbose_name='행동코드'),
        ),
    ]
