# Generated by Django 2.1.5 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_auto_20181130_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='kind',
            field=models.CharField(choices=[('deposit', '입금'), ('withdraw', '출금'), ('default', '기본')], default='default', max_length=20, verbose_name='유형'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='비밀번호'),
        ),
    ]
