# Generated by Django 2.1.5 on 2019-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='입금 주소'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdraw_address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='출금 주소'),
        ),
    ]
