# Generated by Django 2.1.5 on 2019-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_auto_20190415_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='kind',
        ),
        migrations.AddField(
            model_name='wallet',
            name='default_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='공통/기본 주소'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='입금 주소'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdraw_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='출금 주소'),
        ),
    ]
