# Generated by Django 2.0.3 on 2018-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_notification_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('following_new_post', '팔로잉하는 작가의 새 게시물'), ('new_vote_user_voted', '내가 보팅한 글에 타인의 새 보팅'), ('new_comment_user_commented', '내가 댓글단 글에 타인의 새 댓글'), ('new_comment_user_posted', '내가 쓴 글에 타인의 새 댓글')], max_length=40, verbose_name='종류'),
        ),
    ]
