# Generated by Django 2.1.5 on 2019-04-02 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0004_notificationtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtoken',
            unique_together={('user', 'device', 'token')},
        ),
    ]
