# Generated by Django 2.1.5 on 2019-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20190402_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('following_new_post', '팔로잉하는 작가의 새 게시물'), ('new_vote_user_voted', '내가 보팅한 글에 타인의 새 보팅'), ('new_comment_user_commented', '내가 댓글단 글에 타인의 새 댓글'), ('new_comment_user_posted', '내가 쓴 글에 타인의 새 댓글'), ('liked_my_post', '내 포스트에 좋아요를 받았을 때'), ('my_new_follower', '누군가 나를 팔로잉 했을 때')], max_length=40, verbose_name='종류'),
        ),
    ]
